name: Commit Linter
description: Lints Pull Request commit messages with commitlint
author: Wagner Santos
inputs:
  configFile:
    description: >
      Commitlint config file. The .js extension is not supported; use .mjs instead.
      If the file doesn't exist, config-conventional settings will be loaded as a fallback.
    default: ./commitlint.config.mjs
    required: false
  failOnWarnings:
    description: Whether you want to fail on warnings or not
    default: "false"
    required: false
  failOnErrors:
    description: Whether you want to fail on errors or not
    default: "true"
    required: false
  helpURL:
    description: Link to a page explaining your commit message convention
    default: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
    required: false
  commitDepth:
    description: >
      When set to an integer value X, considers only the first X commits from the returned commit list.
      Values less than or equal to zero, or values that cannot be parsed as an integer, are ignored and all commits are linted.
    default: ""
    required: false
  token:
    description: >
      Personal access token (PAT) used to interact with the GitHub API. By default, the automatic
      token provided by GitHub is used. You can see more info about GitHub's default token here:
      https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
    default: ${{ github.token }}
    required: false
outputs:
  results:
    description: >
      JSON-encoded string representing an array of lint results for each analyzed
      commit; parse it with fromJSON in workflows. Each entry contains:
      hash (commit SHA), message (commit message), valid (boolean),
      errors (array of strings), warnings (array of strings).
runs:
  using: docker
  image: docker://wagoid/commitlint-github-action:6.2.1
branding:
  icon: check-square
  color: blue
